#!/usr/bin/env bash
# Materialize the full nodejs-mobile source tree from this patches-only
# branch: clone upstream nodejs/node at the pinned base, apply the patch
# series, overlay the fork-only files, and verify the result byte-for-byte
# against expected-tree.txt.
#
# Usage:
#   scripts/prepare.sh [out_dir]        # default out/
#
# Env overrides (mainly for CI/offline use):
#   UPSTREAM_REPO   git URL or local path (default https://github.com/nodejs/node.git)
#   UPSTREAM_REF    tag/branch to clone   (default: first line of upstream-base.txt)
#   SKIP_VERIFY=1   don't fail on an expected-tree mismatch (prints both hashes)
set -euo pipefail

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
OUT=${1:-"${HERE}/out"}
UPSTREAM_REPO=${UPSTREAM_REPO:-https://github.com/nodejs/node.git}

BASE=$(grep -Ev '^\s*(#|$)' "${HERE}/upstream-base.txt" | head -n1 | tr -d '[:space:]')
UPSTREAM_REF=${UPSTREAM_REF:-${BASE}}
[ -n "${BASE}" ] || { echo "error: no base in upstream-base.txt" >&2; exit 1; }

if [ -e "${OUT}" ]; then
  echo "error: ${OUT} already exists — remove it (or pass another dir) and retry." >&2
  exit 1
fi

echo "1/4 Cloning ${UPSTREAM_REPO} @ ${UPSTREAM_REF} (shallow)..."
git clone --depth 1 --branch "${UPSTREAM_REF}" "${UPSTREAM_REPO}" "${OUT}"
git -C "${OUT}" config user.name  "${GIT_AUTHOR_NAME:-nodejs-mobile}"
git -C "${OUT}" config user.email "${GIT_AUTHOR_EMAIL:-nodejs-mobile@invalid}"

echo "2/4 Applying $(wc -l < "${HERE}/patches/series" | tr -d ' ') patches..."
while IFS= read -r p || [ -n "${p}" ]; do
  [ -z "${p}" ] && continue
  case "${p}" in \#*) continue ;; esac
  # --3way: merge via embedded blob context when upstream drifted; real
  # conflicts still fail loudly. --whitespace=nowarn: byte-exact apply
  # regardless of the caller's apply.whitespace config.
  git -C "${OUT}" am --3way --keep-cr --whitespace=nowarn "${HERE}/patches/${p}" \
    || { echo "error: patch failed: ${p} (resolve in ${OUT}, then 'git am --continue')" >&2; exit 1; }
done < "${HERE}/patches/series"

echo "3/4 Overlaying mobile-src/ (fork-only files)..."
# Enumerate via git, not the raw working dir: an untracked-and-ignored file
# (.DS_Store, editor droppings) must not enter the product tree — it would
# change the tree hash to one CI's clean checkout can never reproduce.
# --cached picks up tracked files (working-tree content), --others
# --exclude-standard picks up new not-yet-committed files from the
# regenerate loop while honoring the gitignores.
MANIFEST=$(mktemp)
trap 'rm -f "${MANIFEST}"' EXIT
( cd "${HERE}/mobile-src" && git ls-files -z --cached --others --exclude-standard . ) > "${MANIFEST}"
( cd "${HERE}/mobile-src" && tar cf - --null -T "${MANIFEST}" ) | ( cd "${OUT}" && tar xf - )
# Stage exactly what the overlay wrote, never `add -A`: a Finder-created
# .DS_Store (or any other droppings in the clone) would otherwise be committed
# into the product tree, whose hash CI's clean checkout can never reproduce.
# -f because some tracked fork files (Xcode project internals) match the tree's
# own .gitignore patterns; the overlay must land them all regardless.
git -C "${OUT}" add -f --pathspec-from-file="${MANIFEST}" --pathspec-file-nul
git -C "${OUT}" commit -q -m "mobile: fork-only files (mobile-src overlay)

Generated by scripts/prepare.sh from the recipe branch. Fork-only files
have no upstream counterpart; they are tracked as plain files in
mobile-src/, not as patches."

echo "4/4 Verifying tree against expected-tree.txt..."
GOT=$(git -C "${OUT}" rev-parse 'HEAD^{tree}')
WANT=$(grep -Ev '^\s*(#|$)' "${HERE}/expected-tree.txt" | head -n1 | tr -d '[:space:]')
if [ "${GOT}" = "${WANT}" ]; then
  echo "OK: reconstructed tree ${GOT} matches expected-tree.txt"
else
  echo "MISMATCH: reconstructed ${GOT} != expected ${WANT}" >&2
  echo "If the difference is intentional (you changed patches/ or mobile-src/)," >&2
  echo "update expected-tree.txt to ${GOT}." >&2
  [ "${SKIP_VERIFY:-0}" = "1" ] || exit 1
fi

echo "Done: ${OUT} is a full nodejs-mobile source tree (base ${BASE})."
echo "Build it as usual, e.g.: cd ${OUT} && ./tools/android_build.sh ..."
